# requirements:
# plugins:
#   - https://github.com/zsh-users/zsh-autosuggestions.git
#   - https://github.com/zsh-users/zsh-syntax-highlighting
#   - https://github.com/zsh-users/zsh-history-substring-search

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="simplified-agnoster"
CASE_SENSITIVE="true"

# completion
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' menu select=2
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion::complete:*' use-cache 1
## manually converted $LSCOLORS using https://geoff.greer.fm/lscolors/
# export _ls_colors="di=1;34:ln=1;36:so=1;31:pi=1;33:ex=1;32:bd=1;34;46:cd=1;34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43"  # standard ls color scheme
local _ls_colors="di=1;36:ln=35:so=32:pi=33:ex=32:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
zstyle ':completion:*:default' list-colors "${(s.:.)_ls_colors}"

export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST  # dumps .zcomdump to cache

# history
HISTFILE="${HOME}/.zsh_history"
HISTSIZE='10000'
HIST_STAMPS="dd/mm/yyyy"
SAVEHIST="${HISTSIZE}"
setopt interactivecomments
setopt hist_ignore_dups
setopt hist_ignore_space
setopt appendhistory
setopt sharehistory
setopt incappendhistory

plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
    zsh-history-substring-search
)
source $ZSH/oh-my-zsh.sh

source ${ZSH}/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ${ZSH}/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# directories
local _tmp="${HOME}/tmp"
if [[ ! -d "${_tmp}" ]]; then
    mkdir "${_tmp}"
fi
local _bin="${HOME}/bin"
if [[ ! -d "${_bin}" ]]; then
    mkdir "${_bin}"
fi

# ENV variables
export LANG=en_US.UTF-8
export EDITOR='vim'
export VIRTUAL_ENV_DISABLE_PROMPT=true
# export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd  # standard ls color scheme
export LSCOLORS=Gxfxcxdxcxegedabagacad
export ltmp="${_tmp}"
export lbin="${_bin}"
export PATH="${PATH}:/${lbin}"

# aliases
if [ "$OSTYPE" != linux-gnu ]; then
    alias ls='gls --color=auto --group-directories-first --human-readable'
fi
alias ll='gls -la --color=auto --group-directories-first'
alias grep='grep --color=auto --exclude-dir=.git'
alias svim='sudo vim'
alias qssh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
